vich_uploader:
    db_driver: orm

    mappings:
        artist_video:
            uri_prefix: /video
            upload_destination: '%kernel.project_dir%/public/video'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
